### ISSUE TITLE
[Feature] Don't push default filters to URL

### ISSUE THREAD

**Issue by Timat123** [porn-vault/porn-vault#1365]
**Is your feature request related to a problem? Please describe.**
The new pagination feature works nicely by embedding all filters into the URL, but the default settings are redundant:
`/#/scenes?page=2&query=null&favoritesOnly=null&bookmarksOnly=null&ratingFilter=0&selectedLabels={"include"%3A[],"exclude"%3A[]}&selectedActors=[]&selectedStudio=&useDuration=null&durationRange=[0,180]&sortBy="relevance"&sortDir="desc"`
should be equivalent to
`/#/scenes?page=2`

**Describe the solution you'd like**
Only settings which are not default should be stored in the URL

**Comment by leadwolf** [comment]
All the filters are stored in the URL so that when copying and pasting the link, you can be sure the all the same filters will be applied. Otherwise, the filters from the last search will be applied.
This is because if a filter is not in the url, it will be taken from the last search.
If we want to be able  to "hide" filters from the url, that means the current url possibly does not represent all the filters of the search.

A potential solution is to have a "get permanent link / generate static url / ..." button that would update the current url to have all the filters.  
This resembles Github: by default, when browsing and viewing files, it shows the latest versions of the files on the current branch. The url is `/blob/{branch}/{path}`. If you press `y`, the url will change to `/blob/{commit}/{path}`. [Here is the gh docs](https://docs.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files)

I think this can be a valid solution, as long as steps are taken to inform the user that he must click the button to generate a static url. Additionally, I don't think the proportion of users saving/sharing specific urls is too high, reducing the potential number of confused users

**Comment by Timat123** [comment]
> If we want to be able to "hide" filters from the url, that means the current url possibly does not represent all the filters of the search.

Why is that? The absence of a property can represent the default value.

If someone sends you a link with missing filters in the url, they were equal to the default value. If you click on that link, PV can treat a missing filter as the default value and you will see the same results because you have the same filters.

**Comment by leadwolf** [comment]
The default value is not guaranteed to be the same across devices

**Comment by Timat123** [comment]
>The default value is the value that was used by the last search.

What was used by the last search is pushed to the URL when you navigate to the scenes, but that does not make it the default value.

You can still define single default values for every filter, and only push the filters from the last search to the URL which are not equal to the default value.

**Comment by leadwolf** [comment]
Ah ok I see what you mean. But right now it still wouldn't work across devices because each filter's value is checked/restored individually.
But we can potentially only use the last searched value of a filter if there aren't any filters at all in the current url. Meaning that the default value would be used for a filter when there is at least 1 other filter in the url and the current filter is absent.
